import { describe, expect, it } from "bun:test";
import { PermissionEngine, PermissionLevel } from "../src/permission/engine.js";
import { readFileTool, editFileTool, shellExecTool, createDefaultToolRegistry } from "@morphic/tools";
import { AgentController } from "../src/loop/controller.js";
import type { ModelProvider, ChatMessage, CompletionOptions, CompletionResult } from "@morphic/providers";

describe("Permission Engine", () => {
  it("Level 2 (Standard) auto-allows read tools", async () => {
    const engine = new PermissionEngine(PermissionLevel.Standard);
    const isApproved = await engine.checkPermission(readFileTool, { path: "foo.txt" });
    expect(isApproved).toBe(true);
  });

  it("Level 2 (Standard) requests approval for edit/exec tools", async () => {
    let prompted = false;
    const engine = new PermissionEngine(PermissionLevel.Standard, async (req) => {
      prompted = true;
      return true;
    });

    const isApproved = await engine.checkPermission(editFileTool, { path: "foo.txt" });
    expect(prompted).toBe(true);
    expect(isApproved).toBe(true);
  });

  it("Blocks dangerous shell commands even in Auto level", async () => {
    const engine = new PermissionEngine(PermissionLevel.Auto);
    const dangerous = await engine.checkPermission(shellExecTool, { command: "rm -rf /" });
    expect(dangerous).toBe(false);
  });
});

describe("Agent Controller Loop", () => {
  it("executes ReAct cycle with tool calls", async () => {
    // Mock Provider that calls create_file tool on turn 1, then answers on turn 2
    let turn = 0;
    const mockProvider: ModelProvider = {
      id: "mock",
      name: "Mock Provider",
      async isAvailable() {
        return true;
      },
      async listModels() {
        return [{ id: "mock-model", name: "Mock Model" }];
      },
      async chat() {
        throw new Error("Not used");
      },
      async chatStream(messages: ChatMessage[], options?: CompletionOptions, onChunk?: any) {
        turn++;
        if (turn === 1) {
          return {
            content: "I will create a file.",
            tool_calls: [
              {
                id: "call_123",
                type: "function",
                function: {
                  name: "create_file",
                  arguments: JSON.stringify({
                    path: "mock_test.txt",
                    content: "Generated by agent",
                  }),
                },
              },
            ],
            finish_reason: "tool_calls",
            model: "mock-model",
          };
        } else {
          const finalMsg = "File created successfully!";
          onChunk?.({ content: finalMsg });
          return {
            content: finalMsg,
            finish_reason: "stop",
            model: "mock-model",
          };
        }
      },
    };

    const tools = createDefaultToolRegistry();
    const permissions = new PermissionEngine(PermissionLevel.Auto);

    const controller = new AgentController({
      provider: mockProvider,
      tools,
      permissions,
      cwd: "/tmp",
    });

    const result = await controller.run("Please create a test file.");
    expect(result).toBe("File created successfully!");
    expect(turn).toBe(2);
  });
});
